# Generated by Django 5.1.1 on 2025-02-18 19:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NumericToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("encrypted_numeric_token", models.CharField(max_length=300)),
                ("attempts", models.IntegerField(default=0)),
                ("is_blocked", models.BooleanField(default=False)),
                ("token_created_at", models.DateTimeField(auto_now_add=True)),
                ("token_expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="numeric_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Numeric Token",
                "verbose_name_plural": "Numeric Tokens",
                "indexes": [
                    models.Index(
                        fields=["user"], name="user_app_nu_user_id_2df663_idx"
                    ),
                    models.Index(
                        fields=["token_expires_at"],
                        name="user_app_nu_token_e_d2da17_idx",
                    ),
                ],
            },
        ),
    ]
