# Generated by Django 5.1.1 on 2024-10-04 21:53

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("list_date", models.DateField()),
                ("list_time_initial", models.DateTimeField()),
                ("list_time_final", models.DateTimeField()),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("M", "MATUTINO"),
                            ("V", "VESPERTINO"),
                            ("N", "NOTURNO"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "type_creation",
                    models.CharField(
                        choices=[("MANUAL", "MANUAL"), ("AUTOMATICO", "AUTOMÁTICO")],
                        max_length=10,
                    ),
                ),
                ("is_enable", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bus List",
                "verbose_name_plural": "Bus Lists",
                "db_table": "bus_list",
            },
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notice",
                "verbose_name_plural": "Notices",
                "db_table": "notice",
            },
        ),
        migrations.CreateModel(
            name="BusListStudent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("end_class_time", models.TimeField()),
                ("is_return", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bus_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="buslist_app.buslist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bus List Student",
                "verbose_name_plural": "Bus List Students",
                "db_table": "bus_list_student",
            },
        ),
    ]
