# Generated by Django 5.1.1 on 2024-10-04 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("buslist_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="busliststudent",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="buslist",
            name="students",
            field=models.ManyToManyField(
                related_name="bus_lists",
                through="buslist_app.BusListStudent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notice",
            name="buslist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="buslist_app.buslist"
            ),
        ),
        migrations.AddField(
            model_name="notice",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
