# Generated by Django 5.1.1 on 2024-12-21 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buslist_app", "0003_notice_viewed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notice",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Notice",
                "verbose_name_plural": "Notices",
            },
        ),
    ]
